//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountryInfro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_Table
    {
        public int Primary_Key { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string Conform_Pass { get; set; }
    }
}
